// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	service "github.com/iTrellis/trellis/service"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              *service.Service `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Endpoint             string           `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Payload              *Payload         `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetService() *service.Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Request) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Request) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Response struct {
	Body                 []byte            `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Header               map[string]string `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

type Payload struct {
	Header               map[string]string `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Payload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "message.Request")
	proto.RegisterType((*Response)(nil), "message.Response")
	proto.RegisterMapType((map[string]string)(nil), "message.Response.HeaderEntry")
	proto.RegisterType((*Payload)(nil), "message.Payload")
	proto.RegisterMapType((map[string]string)(nil), "message.Payload.HeaderEntry")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x65, 0x93, 0xfe, 0x9a, 0x76, 0xf2, 0xab, 0x94, 0xc5, 0x43, 0x08, 0x0a, 0x21, 0xa7, 0xe0,
	0x21, 0x81, 0xd6, 0x82, 0x7f, 0x6e, 0x82, 0xe0, 0x51, 0x56, 0x4f, 0xde, 0x92, 0xee, 0xd0, 0x2e,
	0xa6, 0xd9, 0x98, 0xdd, 0x14, 0xf2, 0x21, 0x14, 0x3f, 0xb2, 0x34, 0xd9, 0x44, 0x29, 0xde, 0x3c,
	0xcd, 0xce, 0xdb, 0x37, 0x6f, 0xde, 0x63, 0x60, 0xb6, 0x43, 0xa5, 0xd2, 0x0d, 0xc6, 0x65, 0x25,
	0xb5, 0xa4, 0x8e, 0x69, 0xfd, 0x99, 0xc2, 0x6a, 0x2f, 0xd6, 0x06, 0x0f, 0xdf, 0x09, 0x38, 0x0c,
	0xdf, 0x6a, 0x54, 0x9a, 0x9e, 0x80, 0x25, 0xb8, 0x47, 0x02, 0x12, 0x4d, 0x99, 0x25, 0x38, 0xbd,
	0x00, 0xc7, 0x90, 0x3d, 0x2b, 0x20, 0x91, 0xbb, 0x98, 0xc7, 0xfd, 0xf0, 0x53, 0x57, 0x59, 0x4f,
	0xa0, 0x3e, 0x4c, 0xb0, 0xe0, 0xa5, 0x14, 0x85, 0xf6, 0xec, 0x56, 0x61, 0xe8, 0x0f, 0x3a, 0x65,
	0xda, 0xe4, 0x32, 0xe5, 0xde, 0xc8, 0xe8, 0xf4, 0xe6, 0x1e, 0x3b, 0x9c, 0xf5, 0x84, 0xf0, 0x93,
	0xc0, 0x84, 0xa1, 0x2a, 0x65, 0xa1, 0x90, 0x52, 0x18, 0x65, 0x92, 0x37, 0xad, 0xa5, 0xff, 0xac,
	0x7d, 0xd3, 0x15, 0x8c, 0xb7, 0x98, 0x72, 0xac, 0x3c, 0x2b, 0xb0, 0x23, 0x77, 0x71, 0x3e, 0x68,
	0xf5, 0x63, 0xf1, 0x43, 0xfb, 0x7f, 0x5f, 0xe8, 0xaa, 0x61, 0x86, 0xec, 0x5f, 0x83, 0xfb, 0x03,
	0xa6, 0x73, 0xb0, 0x5f, 0xb1, 0x31, 0x59, 0x0f, 0x4f, 0x7a, 0x0a, 0xff, 0xf6, 0x69, 0x5e, 0x77,
	0x51, 0xa7, 0xac, 0x6b, 0x6e, 0xac, 0x2b, 0x12, 0x7e, 0x10, 0x70, 0x8c, 0x4f, 0x7a, 0x79, 0xb4,
	0xfd, 0xec, 0x38, 0xc9, 0x6f, 0xcb, 0x87, 0x1c, 0xf6, 0x77, 0x8e, 0x3f, 0x18, 0xba, 0x5b, 0xbd,
	0x2c, 0x37, 0x42, 0x6f, 0xeb, 0x2c, 0x5e, 0xcb, 0x5d, 0x22, 0x9e, 0x2b, 0xcc, 0x73, 0xa1, 0x12,
	0x6d, 0xaa, 0x39, 0x49, 0x62, 0x9c, 0xdd, 0x9a, 0x9a, 0x8d, 0xdb, 0x8b, 0x2f, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x1a, 0xa3, 0x89, 0x61, 0x1a, 0x02, 0x00, 0x00,
}
