// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_create EventType = 0
	EventType_delete EventType = 1
	EventType_update EventType = 2
)

var EventType_name = map[int32]string{
	0: "create",
	1: "delete",
	2: "update",
}

var EventType_value = map[string]int32{
	"create": 0,
	"delete": 1,
	"update": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type RegisterType int32

const (
	RegisterType_memory RegisterType = 0
	RegisterType_etcd   RegisterType = 1
)

var RegisterType_name = map[int32]string{
	0: "memory",
	1: "etcd",
}

var RegisterType_value = map[string]int32{
	"memory": 0,
	"etcd":   1,
}

func (x RegisterType) String() string {
	return proto.EnumName(RegisterType_name, int32(x))
}

func (RegisterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

type Protocol int32

const (
	Protocol_LOCAL Protocol = 0
	Protocol_GRPC  Protocol = 1
	Protocol_HTTP  Protocol = 2
	Protocol_QUIC  Protocol = 3
	Protocol_UDP   Protocol = 4
	Protocol_TCP   Protocol = 5
)

var Protocol_name = map[int32]string{
	0: "LOCAL",
	1: "GRPC",
	2: "HTTP",
	3: "QUIC",
	4: "UDP",
	5: "TCP",
}

var Protocol_value = map[string]int32{
	"LOCAL": 0,
	"GRPC":  1,
	"HTTP":  2,
	"QUIC":  3,
	"UDP":   4,
	"TCP":   5,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

type Service struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Topic                string   `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterEnum("service.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("service.RegisterType", RegisterType_name, RegisterType_value)
	proto.RegisterEnum("service.Protocol", Protocol_name, Protocol_value)
	proto.RegisterType((*Service)(nil), "service.Service")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x40, 0x9b, 0xe6, 0xab, 0x19, 0x14, 0x96, 0x41, 0x24, 0x47, 0x11, 0x0f, 0x12, 0xb1, 0x39,
	0x78, 0xf4, 0xa4, 0xb1, 0xa8, 0x50, 0x30, 0xc6, 0xf4, 0xe2, 0x2d, 0xdd, 0x0c, 0x75, 0x21, 0xc9,
	0x86, 0xcd, 0x36, 0xd0, 0x7f, 0x2f, 0x9b, 0x6c, 0x4f, 0xf3, 0xde, 0x63, 0xf7, 0x30, 0x03, 0x97,
	0x03, 0xa9, 0x51, 0x70, 0x5a, 0xf7, 0x4a, 0x6a, 0x89, 0xa1, 0xd5, 0x5b, 0x82, 0xf0, 0x67, 0x46,
	0xbc, 0x86, 0xa0, 0x96, 0x6d, 0x25, 0xba, 0xd8, 0xb9, 0x71, 0xee, 0xa3, 0xc2, 0x1a, 0x22, 0x78,
	0x5d, 0xd5, 0x52, 0xbc, 0x9c, 0xea, 0xc4, 0x18, 0x43, 0x38, 0x92, 0x1a, 0x84, 0xec, 0x62, 0x77,
	0xca, 0x67, 0xc5, 0x2b, 0xf0, 0xb5, 0xec, 0x05, 0x8f, 0xbd, 0xa9, 0xcf, 0x92, 0xa4, 0x10, 0x6d,
	0x46, 0xea, 0x74, 0x79, 0xea, 0x09, 0x01, 0x02, 0xae, 0xa8, 0xd2, 0xc4, 0x16, 0x86, 0x6b, 0x6a,
	0x48, 0x13, 0x73, 0x0c, 0x1f, 0xfb, 0xda, 0xf4, 0x65, 0x72, 0x07, 0x17, 0x05, 0x1d, 0xc4, 0xa0,
	0x49, 0x9d, 0xff, 0xb4, 0xd4, 0x4a, 0x75, 0x62, 0x0b, 0x5c, 0x81, 0x47, 0x9a, 0xd7, 0xcc, 0x49,
	0x36, 0xb0, 0xca, 0xcd, 0x3e, 0x5c, 0x36, 0x18, 0x81, 0xbf, 0xfd, 0xca, 0x5e, 0xb6, 0xf3, 0x83,
	0xf7, 0x22, 0xcf, 0x98, 0x63, 0xe8, 0xa3, 0x2c, 0x73, 0xb6, 0x34, 0xf4, 0xbd, 0xfb, 0xcc, 0x98,
	0x8b, 0x21, 0xb8, 0xbb, 0xb7, 0x9c, 0x79, 0x06, 0xca, 0x2c, 0x67, 0xfe, 0xeb, 0xe3, 0xef, 0xc3,
	0x41, 0xe8, 0xbf, 0xe3, 0x7e, 0xcd, 0x65, 0x9b, 0x8a, 0x52, 0x51, 0xd3, 0x88, 0x21, 0xd5, 0x76,
	0xda, 0x5b, 0x3d, 0xdb, 0xb9, 0x0f, 0xa6, 0x1b, 0x3e, 0xfd, 0x07, 0x00, 0x00, 0xff, 0xff, 0x7f,
	0xbc, 0x1c, 0xf4, 0x54, 0x01, 0x00, 0x00,
}
