// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package service

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_create EventType = 0
	EventType_delete EventType = 1
	EventType_update EventType = 2
)

var EventType_name = map[int32]string{
	0: "create",
	1: "delete",
	2: "update",
}

var EventType_value = map[string]int32{
	"create": 0,
	"delete": 1,
	"update": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type RegisterType int32

const (
	RegisterType_memory RegisterType = 0
	RegisterType_etcd   RegisterType = 1
)

var RegisterType_name = map[int32]string{
	0: "memory",
	1: "etcd",
}

var RegisterType_value = map[string]int32{
	"memory": 0,
	"etcd":   1,
}

func (x RegisterType) String() string {
	return proto.EnumName(RegisterType_name, int32(x))
}

func (RegisterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

type TransportType int32

const (
	TransportType_GRPC TransportType = 0
	TransportType_HTTP TransportType = 1
	TransportType_QUIC TransportType = 2
)

var TransportType_name = map[int32]string{
	0: "GRPC",
	1: "HTTP",
	2: "QUIC",
}

var TransportType_value = map[string]int32{
	"GRPC": 0,
	"HTTP": 1,
	"QUIC": 2,
}

func (x TransportType) String() string {
	return proto.EnumName(TransportType_name, int32(x))
}

func (TransportType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func init() {
	proto.RegisterEnum("service.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("service.RegisterType", RegisterType_name, RegisterType_value)
	proto.RegisterEnum("service.TransportType", TransportType_name, TransportType_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0xd1, 0xca, 0x82, 0x40,
	0x10, 0x05, 0x60, 0x15, 0xf1, 0xf7, 0x9f, 0x0a, 0x16, 0x9f, 0xa1, 0x2b, 0xa1, 0xba, 0xe8, 0x11,
	0x24, 0xaa, 0x3b, 0x93, 0xed, 0x01, 0x4c, 0x0f, 0x21, 0xa4, 0xbb, 0xcc, 0x4e, 0xc2, 0xbe, 0x7d,
	0x6c, 0xd2, 0xdd, 0xc7, 0x30, 0xe7, 0x70, 0x68, 0x25, 0xde, 0xc2, 0xed, 0x2d, 0x1b, 0x31, 0xc5,
	0x9f, 0x03, 0xcf, 0x43, 0x87, 0xf2, 0x40, 0xff, 0xa7, 0x19, 0x93, 0x68, 0x6f, 0x51, 0x10, 0x65,
	0x1d, 0xa3, 0x15, 0xa8, 0x28, 0xb8, 0xc7, 0x0b, 0x02, 0x15, 0x07, 0xbf, 0x6d, 0x1f, 0xee, 0x49,
	0xb9, 0xa5, 0x75, 0x83, 0xe7, 0xe0, 0x04, 0xfc, 0xcb, 0x8c, 0x18, 0x0d, 0x7b, 0x15, 0x15, 0x39,
	0xa5, 0x90, 0xae, 0x57, 0x71, 0xb9, 0xa3, 0x8d, 0xe6, 0x76, 0x72, 0xd6, 0xf0, 0x52, 0x9d, 0x53,
	0x7a, 0x6e, 0xea, 0x6a, 0x79, 0xba, 0x68, 0x5d, 0xab, 0x38, 0xe8, 0x76, 0xbf, 0x56, 0x2a, 0x79,
	0x64, 0xdf, 0x55, 0xc7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xf0, 0xf7, 0xfa, 0xa4, 0x00,
	0x00, 0x00,
}
