// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterType int32

const (
	RegisterType_Cache RegisterType = 0
	RegisterType_ETCD  RegisterType = 1
)

var RegisterType_name = map[int32]string{
	0: "Cache",
	1: "ETCD",
}

var RegisterType_value = map[string]int32{
	"Cache": 0,
	"ETCD":  1,
}

func (x RegisterType) String() string {
	return proto.EnumName(RegisterType_name, int32(x))
}

func (RegisterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type Protocol int32

const (
	Protocol_LOCAL Protocol = 0
	Protocol_HTTP  Protocol = 1
	Protocol_GRPC  Protocol = 2
)

var Protocol_name = map[int32]string{
	0: "LOCAL",
	1: "HTTP",
	2: "GRPC",
}

var Protocol_value = map[string]int32{
	"LOCAL": 0,
	"HTTP":  1,
	"GRPC":  2,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

// Service 基础服务信息
type Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type RegistOption struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Protocol             string            `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Domain               string            `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Weight               uint32            `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RegistOption) Reset()         { *m = RegistOption{} }
func (m *RegistOption) String() string { return proto.CompactTextString(m) }
func (*RegistOption) ProtoMessage()    {}
func (*RegistOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *RegistOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistOption.Unmarshal(m, b)
}
func (m *RegistOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistOption.Marshal(b, m, deterministic)
}
func (m *RegistOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistOption.Merge(m, src)
}
func (m *RegistOption) XXX_Size() int {
	return xxx_messageInfo_RegistOption.Size(m)
}
func (m *RegistOption) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistOption.DiscardUnknown(m)
}

var xxx_messageInfo_RegistOption proto.InternalMessageInfo

func (m *RegistOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegistOption) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RegistOption) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *RegistOption) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *RegistOption) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *RegistOption) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Payload struct {
	TraceId              string            `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Id                   string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Service              *Service          `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Topic                string            `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Header               map[string]string `protobuf:"bytes,5,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ReqBody              []byte            `protobuf:"bytes,7,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	TraceIp              string            `protobuf:"bytes,8,opt,name=trace_ip,json=traceIp,proto3" json:"trace_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Payload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Payload) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Payload) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Payload) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Payload) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Payload) GetReqBody() []byte {
	if m != nil {
		return m.ReqBody
	}
	return nil
}

func (m *Payload) GetTraceIp() string {
	if m != nil {
		return m.TraceIp
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.RegisterType", RegisterType_name, RegisterType_value)
	proto.RegisterEnum("proto.Protocol", Protocol_name, Protocol_value)
	proto.RegisterType((*Service)(nil), "proto.Service")
	proto.RegisterType((*RegistOption)(nil), "proto.RegistOption")
	proto.RegisterMapType((map[string]string)(nil), "proto.RegistOption.MetadataEntry")
	proto.RegisterType((*Payload)(nil), "proto.Payload")
	proto.RegisterMapType((map[string]string)(nil), "proto.Payload.HeaderEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.Payload.MetadataEntry")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x4e, 0x1c, 0x3b, 0x93, 0x26, 0xb2, 0x46, 0x15, 0x5a, 0x2c, 0x0e, 0x21, 0x48, 0xc8,
	0xf4, 0x90, 0x43, 0x40, 0xa2, 0x80, 0x38, 0x80, 0xa9, 0x28, 0x52, 0x51, 0x2d, 0x93, 0x7b, 0xb5,
	0xf5, 0x8e, 0x92, 0x15, 0x8e, 0xd7, 0x75, 0x96, 0x20, 0xdf, 0xf9, 0x00, 0x3e, 0x19, 0x65, 0xbd,
	0x89, 0xd2, 0x22, 0x0e, 0x55, 0x4f, 0x3b, 0x6f, 0x66, 0x9e, 0xf4, 0xde, 0x9b, 0x85, 0xe1, 0x8a,
	0xd6, 0x6b, 0xbe, 0xa0, 0x69, 0x55, 0x2b, 0xad, 0xd0, 0x33, 0xcf, 0xe4, 0x0d, 0xf8, 0xdf, 0xa9,
	0xde, 0xc8, 0x9c, 0x10, 0xa1, 0x5b, 0xf2, 0x15, 0x31, 0x67, 0xec, 0xc4, 0xfd, 0xcc, 0xd4, 0xc8,
	0xc0, 0xdf, 0x50, 0xbd, 0x96, 0xaa, 0x64, 0xae, 0x69, 0xef, 0xe0, 0xe4, 0xb7, 0x0b, 0x47, 0x19,
	0x2d, 0xe4, 0x5a, 0x5f, 0x56, 0x5a, 0xaa, 0xf2, 0x7e, 0x74, 0x8c, 0x20, 0x30, 0x02, 0x72, 0x55,
	0xb0, 0x8e, 0x19, 0xed, 0x31, 0x3e, 0x86, 0x9e, 0x50, 0x2b, 0x2e, 0x4b, 0xd6, 0x35, 0x13, 0x8b,
	0xb6, 0xfd, 0x5f, 0x24, 0x17, 0x4b, 0xcd, 0xbc, 0xb1, 0x13, 0x0f, 0x33, 0x8b, 0xf0, 0x03, 0x04,
	0x2b, 0xd2, 0x5c, 0x70, 0xcd, 0x59, 0x6f, 0xdc, 0x89, 0x07, 0xb3, 0x67, 0xad, 0xc9, 0xe9, 0xa1,
	0xc0, 0xe9, 0x37, 0xbb, 0x73, 0x56, 0xea, 0xba, 0xc9, 0xf6, 0x94, 0xe8, 0x3d, 0x0c, 0x6f, 0x8d,
	0x30, 0x84, 0xce, 0x0f, 0x6a, 0xac, 0x91, 0x6d, 0x89, 0xc7, 0xe0, 0x6d, 0x78, 0xf1, 0x93, 0xac,
	0x8b, 0x16, 0xbc, 0x73, 0x4f, 0x9d, 0xc9, 0x9f, 0x0e, 0xf8, 0x29, 0x6f, 0x0a, 0xc5, 0x05, 0x3e,
	0x81, 0x40, 0xd7, 0x3c, 0xa7, 0x2b, 0x29, 0x2c, 0xd9, 0x37, 0xf8, 0xab, 0xc0, 0x11, 0xb8, 0x52,
	0x58, 0xb6, 0x2b, 0x05, 0xc6, 0xfb, 0xd8, 0x8d, 0xfb, 0xc1, 0x6c, 0x64, 0x15, 0xdb, 0x6e, 0xb6,
	0xbf, 0xca, 0x31, 0x78, 0x5a, 0x55, 0x32, 0xb7, 0x59, 0xb4, 0x00, 0x67, 0xd0, 0x5b, 0x12, 0x17,
	0x54, 0x33, 0xcf, 0x18, 0x8e, 0x2c, 0xdd, 0x4a, 0x99, 0x9e, 0x9b, 0x61, 0xeb, 0xd4, 0x6e, 0xe2,
	0xe9, 0x3f, 0x31, 0x3d, 0xbd, 0xc3, 0xfa, 0x4f, 0x42, 0x5b, 0x63, 0x35, 0xdd, 0x5c, 0x5d, 0x2b,
	0xd1, 0x30, 0x7f, 0xec, 0xc4, 0x47, 0x99, 0x5f, 0xd3, 0xcd, 0x27, 0x25, 0x9a, 0x03, 0xcf, 0x15,
	0x0b, 0x0e, 0x3d, 0x57, 0xd1, 0x5b, 0x18, 0x1c, 0xc8, 0xb8, 0x4f, 0xaa, 0x0f, 0x3a, 0xc9, 0xc9,
	0xf3, 0xdd, 0xc7, 0xa4, 0x7a, 0xde, 0x54, 0x84, 0x7d, 0xf0, 0x12, 0x9e, 0x2f, 0x29, 0x7c, 0x84,
	0x01, 0x74, 0xcf, 0xe6, 0xc9, 0xe7, 0xd0, 0x39, 0x79, 0x09, 0x41, 0xba, 0xfb, 0x6f, 0x7d, 0xf0,
	0x2e, 0x2e, 0x93, 0x8f, 0x17, 0xed, 0xc2, 0xf9, 0x7c, 0x9e, 0x86, 0xce, 0xb6, 0xfa, 0x92, 0xa5,
	0x49, 0xe8, 0xce, 0x5e, 0x03, 0x64, 0x69, 0xb2, 0xbb, 0xc7, 0x0b, 0xe8, 0x26, 0xbc, 0x28, 0x70,
	0x74, 0x3b, 0xbb, 0xe8, 0x0e, 0xbe, 0xee, 0x19, 0xf8, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x95, 0x0b, 0xd5, 0x2f, 0x77, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCServiceClient is the client API for RPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCServiceClient interface {
	Call(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
}

type rPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewRPCServiceClient(cc *grpc.ClientConn) RPCServiceClient {
	return &rPCServiceClient{cc}
}

func (c *rPCServiceClient) Call(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := c.cc.Invoke(ctx, "/proto.RPCService/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServiceServer is the server API for RPCService service.
type RPCServiceServer interface {
	Call(context.Context, *Payload) (*Payload, error)
}

// UnimplementedRPCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRPCServiceServer struct {
}

func (*UnimplementedRPCServiceServer) Call(ctx context.Context, req *Payload) (*Payload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterRPCServiceServer(s *grpc.Server, srv RPCServiceServer) {
	s.RegisterService(&_RPCService_serviceDesc, srv)
}

func _RPCService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPCService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).Call(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RPCService",
	HandlerType: (*RPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _RPCService_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
