// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistryType int32

const (
	RegistryType_LOCAL RegistryType = 0
	RegistryType_ETCD  RegistryType = 1
)

var RegistryType_name = map[int32]string{
	0: "LOCAL",
	1: "ETCD",
}

var RegistryType_value = map[string]int32{
	"LOCAL": 0,
	"ETCD":  1,
}

func (x RegistryType) String() string {
	return proto.EnumName(RegistryType_name, int32(x))
}

func (RegistryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

// BaseService 基础服务信息
type BaseService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseService) Reset()         { *m = BaseService{} }
func (m *BaseService) String() string { return proto.CompactTextString(m) }
func (*BaseService) ProtoMessage()    {}
func (*BaseService) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *BaseService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseService.Unmarshal(m, b)
}
func (m *BaseService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseService.Marshal(b, m, deterministic)
}
func (m *BaseService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseService.Merge(m, src)
}
func (m *BaseService) XXX_Size() int {
	return xxx_messageInfo_BaseService.Size(m)
}
func (m *BaseService) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseService.DiscardUnknown(m)
}

var xxx_messageInfo_BaseService proto.InternalMessageInfo

func (m *BaseService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseService) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service struct {
	Type                 RegistryType      `protobuf:"varint,1,opt,name=type,proto3,enum=proto.RegistryType" json:"type,omitempty"`
	BaseService          *BaseService      `protobuf:"bytes,2,opt,name=BaseService,proto3" json:"BaseService,omitempty"`
	Endpoint             string            `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetType() RegistryType {
	if m != nil {
		return m.Type
	}
	return RegistryType_LOCAL
}

func (m *Service) GetBaseService() *BaseService {
	if m != nil {
		return m.BaseService
	}
	return nil
}

func (m *Service) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.RegistryType", RegistryType_name, RegistryType_value)
	proto.RegisterType((*BaseService)(nil), "proto.BaseService")
	proto.RegisterType((*Service)(nil), "proto.Service")
	proto.RegisterMapType((map[string]string)(nil), "proto.Service.MetadataEntry")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x4f, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x50, 0x04, 0xa6, 0x42, 0xc8, 0xe8, 0xa1, 0x69, 0x3c, 0x10, 0x4c, 0x94, 0x78, 0xe0,
	0x50, 0x35, 0x21, 0x72, 0xd2, 0xda, 0x78, 0xc1, 0x68, 0x2a, 0x7f, 0x60, 0x6d, 0x27, 0xa4, 0xb1,
	0x5f, 0xd9, 0x5d, 0x9b, 0xec, 0x6f, 0xf7, 0x62, 0xd8, 0x2e, 0x84, 0x7a, 0xda, 0x79, 0x33, 0xef,
	0xbd, 0x7d, 0x0f, 0x46, 0x82, 0x78, 0x9d, 0xc6, 0xb4, 0xa8, 0x78, 0x29, 0x4b, 0xec, 0xe9, 0xc7,
	0x1b, 0xe5, 0x24, 0x04, 0xdb, 0x9a, 0xed, 0x6c, 0x05, 0xce, 0x33, 0x13, 0xf4, 0xd9, 0x50, 0x11,
	0xc1, 0x2e, 0x58, 0x4e, 0xae, 0x35, 0xb5, 0xe6, 0xc3, 0x48, 0xcf, 0xe8, 0x42, 0xbf, 0x26, 0x2e,
	0xd2, 0xb2, 0x70, 0x3b, 0x7a, 0xbd, 0x87, 0xb3, 0x5f, 0x0b, 0xfa, 0x7b, 0xe5, 0x0d, 0xd8, 0x52,
	0x55, 0x8d, 0x72, 0xec, 0x9f, 0x37, 0xf6, 0x8b, 0x88, 0xb6, 0xa9, 0x90, 0x5c, 0x6d, 0x54, 0x45,
	0x91, 0x26, 0xe0, 0x7d, 0xeb, 0x47, 0x6d, 0xe9, 0xf8, 0x68, 0xf8, 0x47, 0x97, 0xa8, 0x15, 0xcc,
	0x83, 0x41, 0x58, 0x24, 0x55, 0x99, 0x16, 0xd2, 0xed, 0xea, 0x14, 0x07, 0x8c, 0x4b, 0x18, 0xe4,
	0x24, 0x59, 0xc2, 0x24, 0x73, 0xed, 0x69, 0x77, 0xee, 0xf8, 0x97, 0xc6, 0xce, 0xa8, 0x17, 0x6f,
	0xe6, 0x1c, 0x16, 0x92, 0xab, 0xe8, 0xc0, 0xf6, 0x56, 0x30, 0x6a, 0x9d, 0x70, 0x02, 0xdd, 0x6f,
	0x52, 0xa6, 0xfe, 0x6e, 0xc4, 0x0b, 0xe8, 0xd5, 0x2c, 0xfb, 0x21, 0xd3, 0xbd, 0x01, 0x8f, 0x9d,
	0xa5, 0x75, 0x7b, 0x05, 0x67, 0xc7, 0xf5, 0x70, 0x08, 0xbd, 0xf5, 0x7b, 0xf0, 0xb4, 0x9e, 0x9c,
	0xe0, 0x00, 0xec, 0x70, 0x13, 0xbc, 0x4c, 0x2c, 0xff, 0x01, 0x9c, 0x57, 0x5e, 0xc5, 0xbb, 0x20,
	0x71, 0x4a, 0x78, 0x0d, 0x76, 0xc0, 0xb2, 0x0c, 0xc7, 0x26, 0xe0, 0x07, 0x53, 0x59, 0xc9, 0x12,
	0xef, 0x1f, 0xfe, 0x3a, 0xd5, 0xf0, 0xee, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xb3, 0x7b, 0x22,
	0xc4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcServcieClient is the client API for GrpcServcie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcServcieClient interface {
	Call(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
}

type grpcServcieClient struct {
	cc *grpc.ClientConn
}

func NewGrpcServcieClient(cc *grpc.ClientConn) GrpcServcieClient {
	return &grpcServcieClient{cc}
}

func (c *grpcServcieClient) Call(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := c.cc.Invoke(ctx, "/proto.GrpcServcie/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServcieServer is the server API for GrpcServcie service.
type GrpcServcieServer interface {
	Call(context.Context, *Payload) (*Payload, error)
}

// UnimplementedGrpcServcieServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcServcieServer struct {
}

func (*UnimplementedGrpcServcieServer) Call(ctx context.Context, req *Payload) (*Payload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterGrpcServcieServer(s *grpc.Server, srv GrpcServcieServer) {
	s.RegisterService(&_GrpcServcie_serviceDesc, srv)
}

func _GrpcServcie_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServcieServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcServcie/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServcieServer).Call(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcServcie_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrpcServcie",
	HandlerType: (*GrpcServcieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _GrpcServcie_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
