// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistryType int32

const (
	RegistryType_LOCAL RegistryType = 0
	RegistryType_ETCD  RegistryType = 1
)

var RegistryType_name = map[int32]string{
	0: "LOCAL",
	1: "ETCD",
}

var RegistryType_value = map[string]int32{
	"LOCAL": 0,
	"ETCD":  1,
}

func (x RegistryType) String() string {
	return proto.EnumName(RegistryType_name, int32(x))
}

func (RegistryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

// BaseService 基础服务信息
type BaseService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseService) Reset()         { *m = BaseService{} }
func (m *BaseService) String() string { return proto.CompactTextString(m) }
func (*BaseService) ProtoMessage()    {}
func (*BaseService) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *BaseService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseService.Unmarshal(m, b)
}
func (m *BaseService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseService.Marshal(b, m, deterministic)
}
func (m *BaseService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseService.Merge(m, src)
}
func (m *BaseService) XXX_Size() int {
	return xxx_messageInfo_BaseService.Size(m)
}
func (m *BaseService) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseService.DiscardUnknown(m)
}

var xxx_messageInfo_BaseService proto.InternalMessageInfo

func (m *BaseService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseService) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service struct {
	Type                 RegistryType      `protobuf:"varint,1,opt,name=type,proto3,enum=proto.RegistryType" json:"type,omitempty"`
	BaseService          *BaseService      `protobuf:"bytes,2,opt,name=BaseService,proto3" json:"BaseService,omitempty"`
	Endpoint             string            `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetType() RegistryType {
	if m != nil {
		return m.Type
	}
	return RegistryType_LOCAL
}

func (m *Service) GetBaseService() *BaseService {
	if m != nil {
		return m.BaseService
	}
	return nil
}

func (m *Service) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.RegistryType", RegistryType_name, RegistryType_value)
	proto.RegisterType((*BaseService)(nil), "proto.BaseService")
	proto.RegisterType((*Service)(nil), "proto.Service")
	proto.RegisterMapType((map[string]string)(nil), "proto.Service.MetadataEntry")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x4f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xc5, 0x4d, 0x42, 0xd3, 0x0b, 0x45, 0xd1, 0xc1, 0x60, 0x55, 0x0c, 0x55, 0x19, 0xa8, 0x18,
	0x32, 0x04, 0x86, 0x8a, 0x4e, 0x50, 0xb2, 0x15, 0x21, 0x99, 0xfe, 0x80, 0xa1, 0x27, 0x14, 0x41,
	0x9d, 0xc8, 0x31, 0x91, 0xfc, 0xed, 0x2c, 0x08, 0xc7, 0xad, 0x9a, 0xc9, 0xf7, 0xfc, 0xde, 0xbb,
	0x7b, 0x0f, 0xc6, 0x0d, 0xe9, 0xb6, 0xfc, 0xa0, 0xac, 0xd6, 0x95, 0xa9, 0x30, 0x72, 0xcf, 0x6c,
	0x09, 0xc9, 0x93, 0x6c, 0xe8, 0xad, 0xe3, 0x10, 0x21, 0x54, 0x72, 0x47, 0x9c, 0x4d, 0xd9, 0x7c,
	0x24, 0xdc, 0x8c, 0x1c, 0x86, 0x2d, 0xe9, 0xa6, 0xac, 0x14, 0x1f, 0xb8, 0xef, 0x3d, 0x9c, 0xfd,
	0x32, 0x18, 0xee, 0x9d, 0x37, 0x10, 0x1a, 0x5b, 0x77, 0xce, 0xf3, 0xfc, 0xa2, 0xbb, 0x92, 0x09,
	0xfa, 0x2c, 0x1b, 0xa3, 0xed, 0xc6, 0xd6, 0x24, 0x9c, 0x00, 0xef, 0x7b, 0x17, 0xdd, 0xca, 0x24,
	0x47, 0xaf, 0x3f, 0x62, 0x44, 0x2f, 0xd8, 0x04, 0xe2, 0x42, 0x6d, 0xeb, 0xaa, 0x54, 0x86, 0x07,
	0x2e, 0xc5, 0x01, 0xe3, 0x02, 0xe2, 0x1d, 0x19, 0xb9, 0x95, 0x46, 0xf2, 0x70, 0x1a, 0xcc, 0x93,
	0xfc, 0xca, 0xaf, 0xf3, 0xee, 0xec, 0xc5, 0xd3, 0x85, 0x32, 0xda, 0x8a, 0x83, 0x7a, 0xb2, 0x84,
	0x71, 0x8f, 0xc2, 0x14, 0x82, 0x2f, 0xb2, 0xbe, 0xfe, 0xff, 0x88, 0x97, 0x10, 0xb5, 0xf2, 0xfb,
	0x87, 0x7c, 0xf7, 0x0e, 0x3c, 0x0c, 0x16, 0xec, 0xf6, 0x1a, 0xce, 0x8e, 0xeb, 0xe1, 0x08, 0xa2,
	0xf5, 0xeb, 0xea, 0x71, 0x9d, 0x9e, 0x60, 0x0c, 0x61, 0xb1, 0x59, 0x3d, 0xa7, 0xec, 0xfd, 0xd4,
	0x05, 0xb9, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x00, 0x35, 0x98, 0xd0, 0x7e, 0x01, 0x00, 0x00,
}
